### ISSUE TITLE
Magento 2 support?

### ISSUE THREAD

**Issue by grantkemp** [QubitProducts/UniversalVariable-Magento-Extension#55]
Hi - will this module be updated to support M2?

**Comment by benjamni** [comment]
Hi @grantkemp. We currently don't have any plans in our development cycle to extend/re-build this module for Magento 2.

**Comment by grantkemp** [comment]
@benjamni  why don't you spec it out - so at least it can be added by others.

**Comment by grantkemp** [comment]
Have closed it by would you be looking at adding Sales Force commerce support ? ( previously demanware)
